// Generated by scripts/set-cf-version.ts at release-build time. Do not edit.
//
// The coreforge channel version: upstream semver plus a 4th ".N" patch-roll
// segment (e.g. "16.3.11.2"). package.json stays 3-segment semver (bun,
// importers, and npm tooling all parse it); only this constant and the
// release tag carry the 4-segment channel version. The dev/source default
// is the bare upstream version.
export const CF_VERSION_OVERRIDE: string | undefined = undefined;
