#!/usr/bin/env bun
/**
 * Inject the coreforge channel version into the release build.
 *
 * Usage: bun scripts/set-cf-version.ts 16.3.11.2 [--reset]
 *
 * Rewrites packages/coding-agent/src/cli/cf-version.generated.ts so the
 * compiled binary reports the 4-segment channel version while package.json
 * stays 3-segment semver. `--reset` restores the dev default (undefined).
 * Run by the mirror's release workflow before `build-binary.ts`; never commit
 * a non-undefined override.
 */
import * as path from "node:path";

const target = path.join(import.meta.dir, "../packages/coding-agent/src/cli/cf-version.generated.ts");
const reset = process.argv.includes("--reset");
const version = process.argv[2];

if (!reset && !/^\d+\.\d+\.\d+(\.\d+)?$/.test(version ?? "")) {
	console.error("usage: set-cf-version.ts <X.Y.Z[.N]> | --reset");
	process.exit(1);
}

const value = reset ? "undefined" : JSON.stringify(version);
await Bun.write(
	target,
	`// Generated by scripts/set-cf-version.ts at release-build time. Do not edit.
//
// The coreforge channel version: upstream semver plus a 4th ".N" patch-roll
// segment (e.g. "16.3.11.2"). package.json stays 3-segment semver (bun,
// importers, and npm tooling all parse it); only this constant and the
// release tag carry the 4-segment channel version. The dev/source default
// is the bare upstream version.
export const CF_VERSION_OVERRIDE: string | undefined = ${value};
`,
);
console.log(`cf-version: ${reset ? "reset to dev default" : `set to ${version}`}`);
